### ISSUE TITLE
How to make Ctrl + F5 work with VScode auto-debug

### ISSUE THREAD

**Issue by jyin1** [DarrenLevine/vscode-auto-debug#1]
I like this plugin to switch between python and C++ debugging, is there a way to set it to make CTRL F5 (Run without debugging) work. Thanks!

**Comment by DarrenLevine** [comment]
Thanks for the feature suggestion! Ctrl-F5 should now work once you update to the latest version (1.0.1) from the extension marketplace.

Change details: [2402e8f](https://github.com/DarrenLevine/vscode-auto-debug/commit/2402e8f5d13be85b4722931686dfdedd4ece6e54?w=1)
