### ISSUE TITLE
Extension telling me there is no active workspaceFolders while there is

### ISSUE THREAD

**Issue by RealAhuraMazda** [DarrenLevine/vscode-auto-debug#3]
Hello,

I have a folder opened is vscode, containing only 3 python files. While I have one of these python files opened and active, when I start the "auto" debug configuration, the extension gives me the error message : "No active workspaceFolders".
Here is the launch configurations that I have.
![Screenshot 2022-07-18 193134](https://user-images.githubusercontent.com/92146833/179571182-8df7dd13-5e20-483d-8b89-a0045965c743.png)

I found out it happens because my launch configurations are stored in the settings.json file of vscode and not in a launch.json file in my workspace folder.
As putting launch configurations in settings.json is supported by vscode, will it be supported by this extension in the future ?

Thanks.

**Comment by DarrenLevine** [comment]
Hi,

I wasn't able to replicate your issue, so I'm thinking perhaps it could be a vscode versioning problem. Just in case that's it, I went ahead and updated the extension's dependencies/packaging to the latest "vscode 1.70.0" versions requirements, and created a new auto-debug extension version 1.0.2 with those changes.

When you have a chance, can you try making sure you're running vscode version 1.70.0 or later, and then pull in the auto-debug version 1.0.2 update to see if that fixes the problem? 

Thanks!
-Darren

**Comment by DarrenLevine** [comment]
closing due to not enough information / unable to replicate

**Comment by fsmed** [comment]
Having the same issue, cant have the auto config in my workspace config file. Maybe this is intended, docs suggest using the launch,json and not workspace config.

Version: 1.73.1
Auto Debug v1.0.2

My workspace config:
`
{
	"folders": [
		{
			"path": "go"
		},
		{
			"path": "py"
		}
	],
	"settings": {},
	"launch": {
		"version": "0.2.0",
		"configurations": [
			{
				"name": "auto",
				"type": "auto-debug",
				"request": "launch",
				"map": {
					"*.py": "Python: Current File",
					"*.go": "GO: Launch"
				}
			},
			{
				"name": "Python: Current File",
				"type": "python",
				"request": "launch",
				"program": "${file}",
				"console": "integratedTerminal"
			},
			{
				"name": "GO: Launch",
				"type": "go",
				"request": "launch",
				"mode": "auto",
				"program": "${fileDirname}",
				"env": {},
				"args": []
			}
		]
	}
}
`

When I move it to a .vscode/launch.json file it works.

`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "auto",
            "type": "auto-debug",
            "request": "launch",
            "map": {
                "*.py": "Python: Current File",
                "*.go": "GO: Launch"
            }
        },
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        },
        {
            "name": "GO: Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }
    ]
}
`

**Comment by Lexikos** [comment]
Same issue here.

VS Code 1.81.1
Auto Debug v1.0.2

I tested on a reasonably clean system, with only this extension enabled. `settings.json` contains only:
```
{
    "launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "auto",
                "type": "auto-debug",
                "request": "launch",
                "map": {
                    "*.htm": "Launch Chrome"
                }
            },
            {
                "name": "Launch Chrome",
                "request": "launch",
                "type": "chrome",
                "file": "${file}"
            }
        ],
        "compounds": []
    }
}
```
*Launch Chrome* works even if a workspace folder is **not** open.

*auto* just gives the error "no active workspaceFolders", even if a workspace folder is open.

The times I would make the most use of this extension are when I open a file or folder with no launch.json... but it just doesn't work.
