### ISSUE TITLE
Multi-OS Switching Support

### ISSUE THREAD

**Issue by fifofonix** [DarrenLevine/vscode-auto-debug#8]
Enhancement Request

As well as the ability to switch based on glob file matching it would be awesome if one could also switch based on the OS type.  The extension works well on Windows and MacOS but I would like to have one auto-debug file synched across devices that works wherever I am.  Of course I would prefer to have debug scripts that run on both OS's but this is not always (easily) possible.

**Comment by michue** [comment]
VS Code provides a way to provide system specific properties as explained in this [answer](https://stackoverflow.com/a/55001070), pointing to the original source [Tasks in VS Code](https://code.visualstudio.com/docs/editor/tasks#_operating-system-specific-properties) which is also applicable to `launch.json`.

My suggestion is: Setup your configurations with this method. That way Auto Debug does not have to care about the OS type and your configuration also works on multiple OS types when selected manually.

**Comment by fifofonix** [comment]
This definitely seems like the way to go.  Thanks @michue.  Closing this.
